### ISSUE TITLE
tooltip不能显示

### ISSUE THREAD

**Issue by cshenger** [beezen/echarts4taro3#1]
如题，图表生成后没有tooltip，无法显示？

**Comment by beezen** [comment]
@cshenger 可以taro info提供一下运行环境,以及提供一下 demo 示例

**Comment by benyun02** [comment]
`vue2` 可以正常显示， `vue3` 需要做如下修改

修改前
```
@touchStart="touchStart"
@touchMove="touchMove"
@touchEnd="touchEnd"
```

修改后
```
@touchstart="touchStart"
@touchmove="touchMove"
@touchend="touchEnd"
```

**Comment by beezen** [comment]
已优化，1.2.0 版本已支持在 taro  vue3 语法中使用。
https://github.com/beezen/echarts4taro3/commit/7a76380f1930a842f62aadbc4fb81011b61cdbd3
