### ISSUE TITLE
页面上做echartsInstance.dispose()销毁，会报错

### ISSUE THREAD

**Issue by zhangyuanliang** [beezen/echarts4taro3#19]
**demo-vue3** pages/index/index.vue 添加销毁代码
```
onBeforeUnmount(() => {
  const echartsInstance = canvas.value.getChart()
  if (echartsInstance) {
    echartsInstance.dispose()
  }
})
```
刷新当前页面，报错信息TypeError: e.removeEventListener is not a function

**Comment by beezen** [comment]
@zhangyuanliang 已修复，https://github.com/beezen/echarts4taro3/pull/20

**Comment by zhangyuanliang** [comment]
请问这样加空函数，有没有起到作用？销毁操作不会引起内存溢出吧？
<img width="1480" alt="image" src="https://github.com/beezen/echarts4taro3/assets/20222232/08543042-613a-4ad7-8832-6a0224bec567">
