### ISSUE TITLE
文件引入到taro中后，小程序代码太大了

### ISSUE THREAD

**Issue by 445022889** [beezen/echarts4taro3#2]
您好，在用Taro开发的过程中使用了您的插件后，图表能正常的显示在小程序中了，非常感谢
但是通过打包后，发现小程序的代码增加了很多，是否有办法减少体积， 比如说CDN之类的，谢谢

**Comment by beezen** [comment]
小程序因为本身的安全性限制，是不支持类似CDN这种动态引用JS的能力的，而是需要将引用的三方代码都打包到发布包中，所以体积会相对变大；
然后，想相对的减小体积有两种方式。一种方式，是 echarts 本身是支持定制化的，比如项目中只需用到柱状图，那可以再echarts官网定制只有柱状图的基础 js；另一种方式，小程序支持分包的模式，可以将图表相关的内容放到单独的分包中，只有在业务逻辑使用时才加载图表相关代码，可一定程度提升体验。
