### ISSUE TITLE
真机调试报错

### ISSUE THREAD

**Issue by zhangyuanliang** [beezen/echarts4taro3#27]
提供的项目demo-vue3里真机调试报错：
<img width="1024" alt="image" src="https://github.com/beezen/echarts4taro3/assets/20222232/85d0ff66-0eb9-40c2-80f1-787f8fba1a10">

**Comment by beezen** [comment]
可以切换到工具的真机调试2.0 ，它应用了新的调试模型，使得调试结果更接近真机表现，同时支持更多特性（例如Canvas接口）。

**Comment by beezen** [comment]
真机调试和真机表现从本质上来讲是不一样的。真机调试更多的是将视图运行于手机，逻辑运行于工具，所以并不是完全的真机表现，建议调试时尽量用真机。
