### ISSUE TITLE
Could not resolve "./echart/index"

### ISSUE THREAD

**Issue by link-zh** [beezen/echarts4taro3#28]
编译过程中控制台提示错误
```
✘ [ERROR] Could not resolve "./echart/index"

    node_modules/echarts4taro3/lib/index.js:1:34:
      1 │ export { default as EChart } from "./echart/index";
```

**Comment by beezen** [comment]
@link-zh 
这个看上去像是编译工具导入配置问题，echarts4taro3 本身是一个 vue 的组件，需要结合 vue-loader 才能使用，可以提供一下项目配置，最好提供 github 上的 Demo 项目地址。

**Comment by link-zh** [comment]
> @link-zh 这个看上去像是编译工具导入配置问题，echarts4taro3 本身是一个 vue 的组件，需要结合 vue-loader 才能使用，可以提供一下项目配置，最好提供 github 上的 Demo 项目地址。

我把预编译关掉就不提示了
```javascript
compiler: {
  type: "webpack5",
  prebundle: {
    enable: false,
  },
},
```
[demo](https://github.com/link-zh/taro-echarts/blob/f091f54cd469832685198669ec255acfe7a1db48/config/index.ts#L27C5-L32C7)

**Comment by beezen** [comment]
> > @link-zh 这个看上去像是编译工具导入配置问题，echarts4taro3 本身是一个 vue 的组件，需要结合 vue-loader 才能使用，可以提供一下项目配置，最好提供 github 上的 Demo 项目地址。
> 
> 我把预编译关掉就不提示了
> 
> ```js
> compiler: {
>   type: "webpack5",
>   prebundle: {
>     enable: false,
>   },
> },
> ```
> 
> [demo](https://github.com/link-zh/taro-echarts/blob/f091f54cd469832685198669ec255acfe7a1db48/config/index.ts#L27C5-L32C7)

我猜测主要是因为 prebundle 是用来预编译 JavaScript 模块的，而它在编译 Vue 组件时发生了异常错误。所以在配置上其实只要移除 echarts4taro3 模块就可以了。类似下面这样：
```javascript
 prebundle: {
        enable: true,
        exclude: ["echarts4taro3"],
      },
```
