### ISSUE TITLE
taro升级到3.5.10之后不显示图了

### ISSUE THREAD

**Issue by zhangzq** [beezen/echarts4taro3#6]
报错信息如下：

![image](https://user-images.githubusercontent.com/3370086/207063068-c8159a9f-deb6-411e-a66f-b59247a5c20f.png)

**Comment by beezen** [comment]
已优化，可使用1.2.0 版本。  [feat: 兼容支持 vue3 语法](https://github.com/beezen/echarts4taro3/commit/7a76380f1930a842f62aadbc4fb81011b61cdbd3)
